cashapp/hermit

docs/content/usage/ci.md
env.go

* Fix docs typo
* Update cli help message

Improve docs

---

archive/archive.go

https://snyk.io/research/zip-slip-vulnerability

Zip slip vulnerability validation.

---

docs/content/usage/ci.md

Add new flag `--raw` as we had a backwards incompatible change it seems.

Update docs for new `--raw` flag

---

state/state.go

It did not chmod -R +w the package directory and it also nuked hermit
itself, which was not ideal.

Fix "clean -p".

---

env.go
state/state.go

If the hermit DB is deleted, executing binaries from any existing
packages would result in an ETag check on each invocation.
I think this behaviour is okay, but it's also not clear to me why the original behaviour was desirable?

Fix infinite ETag check loop if DB is missing.

---

env.go
state/state.go

Basically we only want to trigger an update check on the update
frequency, never every time.

OMG this never ends. I think this finally fixes it.

---

app/commands.go
env.go
manifest/config.go
manifest/loader.go
manifest/loader_test.go
manifest/resolver.go

Refactoring in preparation to adding `HEAD` check for all sources.

Refactor manifest validation

---

app/install_cmd.go
app/uninstall_cmd.go
env.go
go.mod
go.sum
manifest/actions.go
manifest/resolver.go
manifest/resolver_test.go
manifest/triggers.go

Also validate event types when unmarshalling manifest,
add a delete action, and fix triggers so they don't apply to all
installed packages.

Trigger uninstall events

---

cache/source.go
util/run.go

fixes https://github.com/cashapp/hermit/issues/145

Do not use ls-remote after cloning a repo to avoid unnecessary network call

---

app/auto_version_cmd.go
app/main.go
cache/cache.go
github/api.go
manifest/autoversion.go
manifest/autoversion_test.go

Also try $GITHUB_TOKEN if $HERMIT_GITHUB_TOKEN is not set.

Make auto-version use Github API client.

---

app/auto_version_cmd.go
app/exec_cmd.go
app/main.go
it/full/spec/it_spec.sh

Environments will stack.
Fixes #174.

Allow execution of binaries from other environments.

---

app/upgrade_cmd.go
env.go
manifest/resolver.go

Sync package sources before upgrade.

---

.golangci.yml
app/commands.go
app/validate_cmd.go
app/validate_script_cmd.go
go.mod
go.sum
manifest/triggers.go

Port alecthomas/shreq over as a subcommand.

---

docs/content/usage/management.md

Update docs for `hermit update` to include information on hermit updating itself.

Update docs for `hermit update`

---

state/state.go

It's really small, but it's been bothering me...

fix: change message when no update required

---

cache/cache.go

This should hopefully provide some relief from transient upstream
interruptions.

fix: retry downloads 3 times before giving up

---

shell/files/activate.tmpl.sh

Closes https://github.com/cashapp/hermit/pull/268
Fixes https://github.com/cashapp/hermit/issues/262

check if deactivate-hermit is defined before calling it

---

manifest/autoversion/html.go
manifest/autoversion/testdata/htmlattr.expected.hcl
manifest/autoversion/testdata/htmlattr.http
manifest/autoversion/testdata/htmlattr.input.hcl
manifest/config.go

Useful for pages with links where the text does not contain the version.

feat: allow HTML auto-versioning to use attrs

---

app/validate_source_cmd.go
env.go
manifest/config_test.go
manifest/resolver.go
manifest/resolver_test.go
state/state.go

Reduces some duplication.
cc @nmahendru

refactor: use platform.Platform struct inside manifest.Config

---

go.mod
go.sum

https://github.com/gabriel-vasile/mimetype/pull/308

fix: upgrade mimetype to include TAR fix

---

.golangci.yml
app/auto_version_cmd.go
app/manifest_add_digests_cmd.go
integration/integration_test.go
manifest/config.go
manifest/digest/digest.go
manifest/loader.go
manifest/resolver.go
state/state.go

feat: automatically add digests when auto-versioning

---

.github/workflows/ci.yml
docs/content/packaging/schema/auto-version.md
docs/content/packaging/schema/channel.md
docs/content/packaging/schema/darwin.md
docs/content/packaging/schema/html.md
docs/content/packaging/schema/linux.md
docs/content/packaging/schema/manifest.md
docs/content/packaging/schema/platform.md
docs/content/packaging/schema/version.md
docs/content/usage/user-config-schema.hcl

This will catch docs build failures before they get to deploy time.

fix: add docs build to main CI pipeline

---

docs/content/usage/user-config.md

This reverts commit a6fbc4358130d27a2a453b077ab0c1aa12faf87e.

Revert "docs(usage/user-config): include the correct path for the schema (#355)"

---

app/exec_cmd.go
docs/docs/packaging/reference.md
integration/integration_test.go
integration/testdata/testenv3/packages/testbin1.hcl
manifest/triggers.go

I'm not 100% sure this is a good idea, as it could easily lead to performance issues, but in some situations I think it could be quite useful.

Add "exec" trigger.

---

env.go
integration/integration_test.go
integration/testdata/testenv4/bin/README.hermit.md
integration/testdata/testenv4/bin/activate-hermit
integration/testdata/testenv4/bin/hermit
integration/testdata/testenv4/bin/hermit.hcl
integration/testdata/testenv4/packages/other.hcl
integration/testdata/testenv4/packages/other.sh
integration/testdata/testenv4/packages/runtimedep.hcl
integration/testdata/testenv4/packages/runtimedep.sh
integration/testdata/testenv4/packages/testbin1.hcl
integration/testdata/testenv4/packages/testbin1.sh
integration/testdata/testenv4/packages/testbin2.hcl
integration/testdata/testenv4/packages/testbin2.sh

Fixes https://github.com/cashapp/hermit/issues/368. See individual commit messages for details.

fix: prioritize runtime deps envars

---

state/state.go
state/state_test.go

Hermit ensures all binaries for a package have been linked.
This resolves crashes that occur as a result of adding [rust-analyzer][1].
[1]: https://github.com/cashapp/hermit-packages/pull/300

state: links any missing binaries

---

state/state.go
state/state_test.go

These changes fixes two bugs happen when hermit download and relink due
to manifest destination changes for a given package.
1. relink is skipped due to only checking the existance for the link.
Instead, link destination should also be checked.
2. relink failed due to link exists previously.  => solved by remove the
link directories prior to creation

fix: clear binaries dir before relink and make sure link paths are the same

---

util/flock/flock.go

There was a race condition that enabled multiple processes to acquire the same lock file. Consider the following sequence:
- Process A successfully acquires lock
- Process B enters acquire function
- Process B calls unix.Open
- Process A calls release(), deleting the lock file
- Process B calls unix.Flock on the still-open file descriptor, successfully locking the now deleted file.
- Process C successfully acquires lock on newly created lock file
After this sequence both B and C hold the lock. To resolve this race, we can simply avoid removing the file. This is what e.g. dpkg does: the /var/lib/dpkg/lock file is always present under normal circumstances.
The issue was discovered by repeatedly running TestContinueFlock:
```
=== RUN   TestContinueFlock
flock_test.go:85: Did not expect an …
```

fix(flock): race condition in acquire

---

env.go

...by only parsing installed packages for their environment variables if we are in a deactivated hermit environment. When activated, the parent shell will have already passed the new process all environment variables, including packages that were installed after initial activation. Parsing the HCL configs of all installed packages introduces some overhead. This can be non-negligible when hermit-managed packages are used a large number of times - for instance with javac or rustc.
Here is a very exaggerated example on a project with 42 installed packages:
Before change:
```bash
$ time make --version > /dev/null
real    0m0.143s
user    0m0.136s
sys     0m0.033s
```
After change:
```bash
$ time make --version > /dev/null
real    0m0.013s
user    0m0.013s
sys     0m0.000s
```
No hermit: …

perf(exec): improve performance

---

cache/cache.go

This PR make hermit returns exit.Unavailable (101) in exit code to indicate download error.

fix: return exit.Unavailable(101) on download error

---

Makefile
app/commands.go
app/exec_cmd.go
app/update_cmd.go

```
hermit --no-self-update ...
```
or
```
export HERMIT_SELF_UPDATE=false
```

feat: add a --[no]-self-update flag + envar
