cashapp/hermit

docs/config.toml

Remove edit and breadcrumb menu from docs - as discussed, this is the
preferred appearance.

Remove edit and breadcrumb menu from docs

---

docs/config.toml
docs/content/_index.md

We removed the breadcrumb/edit menu in a previous PR from all pages. This
was a misunderstanding, should have only been done for frontpage.

Add edit menu back on non-frontpage packages

---

app/commands.go

`hermit info` is available, why not `hermit search`?
Also I want to search hermit for a package before I decide to add or activate it in a directory.

hermit search can be used when unactivated

---

docs/themes/geekdoc/layouts/partials/head/custom.html

Minor fix to add some whitespace for what looks visually a bit off.

css: Add padding between icon and breadcrumbs

---

docs/content/packaging/reference.md
manifest/config_test.go
manifest/loader.go
manifest/resolver.go
manifest/resolver_test.go
manifest/version.go

The current set of packages then looks like this:
aws-iam-authenticator (@0, @0.4, 0.4.0)
A tool to use AWS IAM credentials to authenticate to a Kubernetes cluster.
awscli (@2.2, @2, @stable, @2.0, @2.1, 2.0.40, 2.1.26, 2.2.4)
The AWS Command Line Interface (CLI) is a unified tool to manage your AWS services.
bash (@5, @5.1, @stable, 5.1.4)
Bash is the GNU Project's shell—the Bourne Again SHell. This is an sh-compatible shell that incorporates useful features from the Korn shell (ksh) and the C
shell (csh).
bazel (@4, @4.0, @stable, 4.0.0)
Bazel is an open-source build and test tool similar to Make, Maven, and Gradle.
dynamosql (@0, @0.0, 0.0.1, 0.0.2)
DynamoDB SQL CLI
envoy (@1.11, @1.12, @1, @1.17, @1.16, @1.15, @1.14, @1.13, @stable, 1.11.1, 1.11.2, 1.12.0, 1.12.1, 1.12.2, 1.12.3, …

Synthesise @stable, @<MAJOR> and @<MAJOR>.<MINOR> channels.

---

docs/themes/geekdoc/layouts/partials/head/custom.html

An initial PR fixed the spacing of the items in the breadcrumbs between
icon and rest. Here we also fix the spacing around the separator `/`.
Before
After (double spaced on dev server 🤷‍♀️)

docs: Fix breadcrumb spacing

---

manifest/resolver_test.go
manifest/triggers.go

Previously any run command with arguments would need to be two separate
attributes in the configuration, eg.
on run { cmd = "chmod" args = ["-R", "+w", "${root}" ] }
Now `cmd` will be split via shellquote into command + arguments prior to
appending `args`:
on run { cmd = "chmod -R +w ${root}" }
This is backwards compatible as `args` are appended anyway.

Simplify run actions.

---

app/commands.go
app/main.go
shell/bash.go
shell/files/activate.tmpl.sh
shell/posix.go
shell/shell.go
shell/zsh.go

eg.
🐚 ~/Development/hermit-packages-opensource $
rather than
hermit-packages-opensource🐚 ~/Development/hermit-packages-opensource $

Introduce a flag for configuring a short prompt.

---

manifest/resolver.go

This had broken `hermit search` (without args).

Don't pin search regex.

---

docs/content/packaging/schema/run.md
go.mod
go.sum
manifest/config.go
manifest/config_test.go
manifest/loader.go
manifest/resolver.go

This will allow the following:
version "1.13.5" {
darwin {
arch = "arm64"
source = "https://golang.org/dl/go${version}.${os}-amd64.tar.gz"
}
}
version "1.14.4" {
darwin {
arch = "arm64"
source = "https://golang.org/dl/go${version}.${os}-amd64.tar.gz"
}
}
...
To be expressed as:
version "1.13.5" "1.14.4" {
darwin {
arch = "arm64"
source = "https://golang.org/dl/go${version}.${os}-amd64.tar.gz"
}
}

Support multiple versions in a single block.

---

app/commands.go
envars/ops.go
envars/ops_test.go

eg. This would not get reverted:
PATH: "${HERMIT_ENV}/node_modules/.bin:${NPM_CONFIG_PREFIX}/bin:${PATH}",
Fixes #47

Fix prepend op not reverting multiple paths in a single op.

---

cmd/geninstaller/install.sh.tmpl

On first-use, `~/bin` is not in the user's path and the instructions for `shell-hooks` don't work out of the box.
Prefix the `shell-hooks` line to include `$HERMIT_BIN_INSTALL_DIR`.
Also, move the `shell-hooks` step up because narratively it makes more sense.

Give a working step for shell-hooks

---

app/commands.go
env.go
env_test.go
state/state.go

1. When execing a package the package itself was included in the
dependencies, would download and install, then re-download itself.
2. Second bug was that the last check time for channels in the DB was
being overwritten with a zero time resulting in a re-check on every
execution.

Two bug fixes.

---

shell/shell.go
sources/sources.go

Also fixes an issue where running the `main` via IntelliJ ends up in an infinite loop in shell detection.

Fix a panic on invalid source

---

app/commands.go
env.go
env_test.go
state/state.go

This wasn't following the current convention of mutating the package in
place. Better to stick to convention than half change.

Revert previous logic that returned a cloned copy of mutated packages.

---

app/commands.go
docs/content/packaging/schema/auto-version.md
docs/content/packaging/schema/version.md
manifest/autoversion.go
manifest/autoversion_test.go
manifest/config.go

This requires explicit opt-in via a new configuration block
"auto-version".

Add command for auto-versioning from GitHub releases.

---

docs/content/packaging/schema/auto-version.md
manifest/autoversion.go
manifest/config.go

This will allow for more flexibility when matching upstream versions.

Allow auto-version to extract version numbers via a regex.

---

docs/content/packaging/tutorial.md

I think that's where they are intended to go now ([example](https://github.com/cashapp/hermit-packages/pull/17))

fix link to submit PR to hermit-packages

---

cmd/gendocs/main.go
docs/content/packaging/schema/auto-version.md
docs/content/packaging/schema/channel.md
docs/content/packaging/schema/darwin.md
docs/content/packaging/schema/manifest.md
docs/content/packaging/schema/on.md
docs/content/packaging/schema/platform.md
docs/content/packaging/schema/version.md
manifest/config.go
manifest/config_test.go

Currently there are only "linux" and "darwin" blocks and to match a CPU
architecture the "arch" attribute must be specified. This is not
obvious.
This adds a "platform" block that accepts a set of platform attributes
to match against, such as CPU, OS, perhaps libc version in the future,
and so on.
eg.
platform linux amd64 { ... }
platform darwin { ... }

Generalise platform matching.

---

README.md
docs/content/about/_index.md

Add Slack channel link to #cashapp at Gophers Slack to README and docs.

docs: Add slack channel link

---

cmd/geninstaller/install.sh.tmpl

On docker containers, these might not be set. This prints out a more descriptive error

is `id` instead of $USER or $GID in the installation script

---

cmd/geninstaller/install.sh.tmpl

When hermit creates ~/bin/hermit, ensure that `$XDG_CACHE_HOME` and
`$HOME` are not expanded in it, but rather use those variables. This
allows the user to change XDG_CACHE_HOME/HOME and have hermit adapt to
those changes, and also accommodates different contents of those
variables on a NFS shared home directory or similar.
It also fixes a subtle bug where the installer script downloaded would
run and put hermit in $HERMIT_EXE but then go to run it from a hardcoded
location that may be different to $HERMIT_EXE.

Late bind XDG_CACHE_HOME and HOME in ~/bin/hermit

---

shell/bash.go

No point of exporting `PROMPT_COMMAND` as the function `change_hermit_env` won't be in the subshells anyway.

Do not export PROMPT_COMMAND on bash

---

app/commands.go
app/main.go
app/userconfig.go
docs/Makefile
docs/content/packaging/schema/channel.md
docs/content/packaging/schema/darwin.md
docs/content/packaging/schema/linux.md
docs/content/packaging/schema/manifest.md
docs/content/packaging/schema/platform.md
docs/content/packaging/schema/version.md
docs/content/usage/ci.md
docs/content/usage/updates.md
docs/content/usage/user-config-schema.hcl
docs/content/usage/user-config.md
manifest/config.go

This allows us to:
1. Generate a schema for the documentation.
2. Extend it with configuration that is not mapped directly to flags.
3. Programmatically update the configuration file.

Use a custom HCL schema for ~/.hermit.hcl.

---

app/commands.go
env.go
manifest/resolver.go

Removes this warning on packages that are not supported on the current architecture:
```
warn: invalid manifest reference python3-3.7 in python3.hcl: https://github.com/cashapp/hermit-packages.git/python3.hcl: python3-3.7: no binaries or apps provided
```
Now, instead when searching for packages:
```
$ hermit search python
python3 (@3, @3.9, @latest, 3.7 (architecture not supported), 3.9.5)
Python is a programming language that lets you work quickly and integrate systems more effectively.
```
This notification is also shown when listing for packages on an environment with the unsupported dependency.
Finally, installing, upgrading to, or executing such packages results in an error.

Mark unsupported packages in "hermit search" and fail to install them

---

app/commands.go
env.go
manifest/config.go
manifest/resolver.go

Running `hermit test python3` on a broken package prints out:
```
warn: python3: darwin:arm64: file:///Users/juho/Development/hermit-packages/python3.hcl: python3-3.7: no source provided
warn: python3: darwin:amd64: file:///Users/juho/Development/hermit-packages/python3.hcl: python3-3.7: no binaries or apps provided
warn: python3: linux:arch: file:///Users/juho/Development/hermit-packages/python3.hcl: python3-3.7: no source provided
warn: python3: linux:amd64: file:///Users/juho/Development/hermit-packages/python3.hcl: python3-3.7: no source provided
fatal:hermit: python3-3.7 failed to resolve on all platforms
```

Test resolving all versions when running "hermit test"

---

archive/archive.go
archive/archive_test.go
manifest/config_test.go
manifest/manifesttest/pkgbuilder.go
manifest/resolver.go
manifest/resolver_test.go
state/state.go
state/state_test.go
state/stateutils_test.go

To facilitate this, archive.Extract() now returns a finalisation
function that makes the package directory immutable. The hooks run in
between extraction and finalisation.
Fixes #1

Unpack hooks now run prior to the package being made immutable.

---

manifest/resolver.go
manifest/resolver_test.go

This is a very common source of bugs in manifests in my experience, and
should never be used in practice.

Explicitly error if relative paths are used in hooks.

---

env.go

This change means that manifests only supporting `linux-arm64` will not pass the validation. It unifies the core packages across validations, though.

Use core platforms when validating manifests

---

app/commands.go
app/main.go
env.go
env_test.go
hermittest/envfixture.go

Gives an error like this when testing a package if there is a source for any platform that can not be resolved with `HEAD`:
```
fatal: error fetching https://downloads.haskell.org/~cabal/cabal-install-3.4.0.0/cabal-install-3.4.0.0-aarch64-darwin-sierra.tar.xz: 404 Not Found
```
Checked by testing packages from `A` to `E`, and the cabal error above is the only error returned.

verify package sources with HTTP HEAD when validating packages

---

app/commands.go
app/user_config.go
docs/content/usage/user-config-schema.hcl
shell/files/activate.tmpl.sh
shell/shell.go

Add an option (both a flag and a .hermit.hcl field) to tell hermit not
to make changes to the prompt when activating an environment.
The "prompt" option is an enum with the values "env", "short", and
"none". "env" is the same as the current prompt - the environment name
and hermit icon in the prompt. "short" is the same as the short-prompt
option - just the hermit icon in the prompt. "none" prevents hermit from
changing the prompt at all.
This subsumes the short-prompt option. As a CLI flag, it has been made
hidden, but is still present for backward compatibility. If both
"prompt" and "short-prompt" are set, "short-prompt" will override
whatever has been set for "prompt".

Add a "prompt" option to leave the prompt alone

---

app/commands.go
app/main.go
cache/cache.go
env.go
github/api.go
github/http.go
go.mod
go.sum
hermittest/envfixture.go
manifest/infer.go
manifest/infer_test.go
manifest/resolver.go
manifest/validate.go
platform/platform.go
state/state.go
state/stateutils_test.go
ui/ui.go

This will attempt to infer a manifest from the given download artefact.
It is not super comprehensive but should at the very least check that
there are valid URLs. Only works on GitHub.
```console
$ hermit manifest create https://github.com/mattn/goreman/releases/download/v0.3.7/goreman_v0.3.7_darwin_amd64.zip
// Relative glob from $root to individual terminal binaries.
binaries = []
// Platform-specific configuration. <attr> is a set regexes that must all match against one of CPU, OS, etc..
platform "darwin" "amd64" {
// URL for source package.
source = "https://github.com/mattn/goreman/releases/download/v${version}/goreman_v${version}_${os}_${arch}.zip"
}
// Platform-specific configuration. <attr> is a set regexes that must all match against one of CPU, OS, etc..
platform "darwin" …
```

Add "hermit manifest create <url>".

---

.gitignore
archive/archive.go
archive/archive_test.go
archive/testdata/directory/foo
cache/cache.go
cache/source.go

This PR adds git repos as package sources. If the `source` ends with `.git` it is interpreted as a git repo, and it is fetched by cloning the default branch. This should allow us to serve scripts from a repo via hermit.
We could improve this in the future by allowing non-default branches or tags.

Git repo as package source

---

cache/cache.go

As we clone git repos to the cache now, the cache can contain directories.

Correctly clean directory caches of git repos

---

go.mod
go.sum
manifest/config.go
manifest/infer.go
manifest/infer_test.go

Which results in a change from this:
// Relative glob from $root to individual terminal binaries.
binaries = []
// Platform-specific configuration. <attr> is a set regexes that must all match against one of CPU, OS, etc..
platform "darwin" "amd64" {
// URL for source package. Valid URLs are Git repositories (using .git suffix), Local Files (using file:// prefix), and Remote Files (using http:// or https:// prefix)
source = "https://github.com/lima-vm/lima/releases/download/v${version}/lima-${version}-${os}-${xarch}.tar.gz"
}
// Platform-specific configuration. <attr> is a set regexes that must all match against one of CPU, OS, etc..
platform "darwin" "arm64" {
// URL for source package. Valid URLs are Git repositories (using .git suffix), Local Files (using file:// prefix), and Remote …

Update to newer HCL library that doesn't serialise field descriptions.

---

docs/themes/geekdoc/static/custom.css

Rendering as this:
Instead of this:

Prevent code spans from wrapping in tables.

---

app/exec_cmd.go
app/install_cmd.go
env.go
env_test.go

Fixes https://github.com/cashapp/hermit/issues/143
Previously, when running `hermit install` and the sources could not be cloned, the return code was a success. This is because we were resolving installed packages, and ignoring the resolution errors at `ListInstalled`. This then marked the source as synchronised, and it was not attempted again. `ListInstalled` then returned 0 packages, and the execution was a success.
After this fix:
```
./bin/hermit install               
error:https://github.com/cashapp/hermit-packages.git: Cloning into '/Users/juho/Library/Caches/hermit/sources/6682e3c492bdd27fac0db80685cb1df7bd13fda32bb9765ca15e895df13eb3cc-113676931'...
fatal: unable to access 'https://github.com/cashapp/hermit-packages.git/': Could not resolve host: github.com
fatal:hermit: git sync …
```

Fail hermit install if the packages can not be installed due to failure to sync sources

---

cmd/geninstaller/install.sh.tmpl

Decided to fix the failure when running parallel installations as it seems there are no easy portable locking solutions for bash scripts.
Fixes https://github.com/cashapp/hermit/issues/144

Do not fail if multiple installations are running in parallel

---

env.go
it/full/spec/it_spec.sh

Fixes this error when executing Hermit binaries in a symlinked environment:
```
fatal:hermit: can not execute a Hermit managed binary from a non active environment
```
Fixes https://github.com/cashapp/hermit/issues/149

Fix binary execution in symlinked environment

---

bin/gendocs
bin/geninstaller
bin/go-main-stubs
cmd/geninstaller/install.sh.tmpl
cmd/geninstaller/main.go
github/api.go
go.mod
go.sum

The first version installed will be installed as `~/bin/hermit` and
`~/bin/hermit-<channel>`. Subsequent channels will be installed just as
`~/bin/hermit-<channel>`.
Homebrew is supported by trying /opt/homebrew/bin and /usr/local/bin
before ~/bin.

Support multiple installed channels + Homebrew.

---

app/main.go
cache/cache.go
hermittest/envfixture.go
state/state.go
state/stateutils_test.go

The majority of the arguments being passed into the env.Open() were for
the cache, which was a bit icky.

Factor cache construction out of the Env constructor.

---

env.go

Fixes #171
Looks like this:
```
🐚 ~/…/hermit/packages $ go run ../cmd/hermit test bash                                                                                                                                                           aat/test-shows-output 2921ms
fatal:hermit: /Users/aat/Library/Caches/hermit/pkg/bash-5.1/bash: --missing-flag: invalid option
Usage:	/Users/aat/Library/Caches/hermit/pkg/bash-5.1/bash [GNU long option] [option] ...
/Users/aat/Library/Caches/hermit/pkg/bash-5.1/bash [GNU long option] [option] script-file ...
GNU long options:
--debug
--debugger
--dump-po-strings
--dump-strings
--help
--init-file
--login
--noediting
--noprofile
--norc
--posix
--pretty-print
--rcfile
--restricted
--verbose
--version
Shell options:
-ilrsD or -c command or -O shopt_option …
```

Include command output when test fails.

---

app/command_info_test.go
app/info_cmd.go
app/install_cmd.go
app/log_test.go
app/test_cmd.go
app/uninstall_cmd.go
env.go
it/full/run.sh
manifest/package_selector.go
manifest/package_selector_test.go
manifest/resolver.go

This allows it to be used directly in the CLI structs, simplifying a bit
of code.

GlobSelector implements TextUnmarshaler

---

manifest/version.go
manifest/version_test.go

Previously, the "orig" field used by `Version.String()` used the original string, including prerelease and metadata. This resulted in channel synthesis failing with eg.
warn: invalid manifest reference openjdk@17+arm64 in openjdk.hcl: @17+arm64: no version found matching 17+arm64.*
warn: invalid manifest reference openjdk@17.0+arm64 in openjdk.hcl: @17.0+arm64: no version found matching 17.0+arm64.*
This change correctly clears the non-base version information.

fix: cleaning a version removes everything but the base version

---

docs/content/packaging/schema/auto-version.md
docs/content/packaging/schema/channel.md
docs/content/packaging/schema/chmod.md
docs/content/packaging/schema/copy.md
docs/content/packaging/schema/darwin.md
docs/content/packaging/schema/delete.md
docs/content/packaging/schema/html.md
docs/content/packaging/schema/linux.md
docs/content/packaging/schema/manifest.md
docs/content/packaging/schema/message.md
docs/content/packaging/schema/on.md
docs/content/packaging/schema/platform.md
docs/content/packaging/schema/rename.md
docs/content/packaging/schema/run.md
docs/content/packaging/schema/version.md
manifest/config.go
manifest/resolver.go
manifest/resolver_test.go

This removes a lot of boilerplate from packages with less 1:1 mappings of version to URL.
eg. This
```hcl
description = "A tool to format C/C++/Java/JavaScript/JSON/Objective-C/Protobuf/C# code."
binaries = ["clang-format"]
version "10.0.0-20211020" {
platform linux {
source = "https://github.com/muttleyxd/clang-tools-static-binaries/releases/download/master-f3a37dd2/clang-format-10_linux-amd64"
on unpack { rename { from = "${root}/clang-format-10_linux-amd64" to = "${root}/clang-format" } }
}
platform darwin {
source = "https://github.com/muttleyxd/clang-tools-static-binaries/releases/download/master-f3a37dd2/clang-format-10_macosx-amd64"
on unpack { rename { from = "${root}/clang-format-10_macosx-amd64" to = "${root}/clang-format" } }
}
}
version "11.0.0-20211020" {
platform linux { …
```

Add support for package defined local vars.

---

docs/content/packaging/reference.md
manifest/resolver.go

Useful for packages that are identical except name, eg. clang-format,
clang-tidy, etc. We can symlink the packages.

feat: add "${name}"

---

app/activate_cmd.go
app/commands.go
app/exec_cmd.go
app/main.go
app/manifest_create_cmd.go
cache/cache.go
cache/git.go
cache/github.go
cache/http.go
cache/source.go
cmd/hermit/main.go
env.go
github/api.go
go.mod
go.sum
hermittest/envfixture.go
manifest/infer.go
manifest/infer_test.go
manifest/validate.go
ui/level_string.go
ui/logger.go

1. "hermit test" did not paginate private GitHub release results
2. Added caching to the GH client.
3. Added HTTP tracing.
4. Fixed a bug where command-line flags would not set the log-level
early enough.
5. Refactored the download strategies into PackageSource
implementations.
6. Fixed a bug where ETag checks weren't using the fast HTTP client.
7. Factored out HTTP downloader function from the Cache into
PackageSources.
8. Made PackageSources not use private internals of Cache.
9. Reusable HTTPSource().
10. Implemented a githubReleaseSource with proper ETag checks.
11. Don't retrieve _all_ GH releases when checking for just one.
12. Increase GH release listing pagination size to the max of 100.
There's still some slight unavoidable weirdness with logging. Because
Hermit does a bit of …

fix: many many bugs fixed and refactorings done

---

app/main.go
cache/github.go

This change allows Hermit API users to control which repositories auth
tokens are used against.

fix: GH release downloads with repo-restricted tokens

---

manifest/config_test.go
manifest/resolver.go
manifest/resolver_test.go

This is particularly for when people use `pkg@version`

feat: improve missing package error message

---

app/env_cmd.go
envars/ops.go
envars/ops_test.go
it/full/spec/it_spec.sh
shell/files/activate.tmpl.sh

This works be storing the JSON-encoded operations for an environment, 
rather than the explicit values for each environment variable. This 
allows Orc's Op.Revert functionality to correctly mutate each 
environment variable as it is being restored, rathern than blindly 
overwriting.
Fixes #218

fix: don't overwrite user-modified envars

---

app/main.go
go.mod
go.sum

Usage: hermit env [<name> [<value>]]
Manage environment variables.
Without arguments the "env" command will display environment variables for the active
Hermit environment.
Passing "<name>" will print the value for that environment variable.
Passing "<name> <value>" will set the value for an environment variable in the active
Hermit environment."
Arguments:
[<name>]     Name of the environment variable.
[<value>]    Value to set the variable to.
Flags:
-h, --help                 Show context-sensitive help.
--version              Show version.
-d, --debug                Enable debug logging.
-t, --trace                Enable trace logging.
-q, --quiet                Disable logging and progress UI, except fatal errors
($HERMIT_QUIET).
--level=auto           Set minimum log level …

chore: separate command flags in help

---

app/install_cmd.go
app/search_cmd.go
app/update_cmd.go
app/upgrade_cmd.go
env.go
sources/git.go

This can be used eg. in CI to force updates to the latest of all
dynamically versioned packages.

feat: sync channels on "hermit update"

---

app/commands.go
app/main.go
app/validate_cmd.go
app/validate_script_cmd.go

This fixes an issue where "validate script" was available outside an
env.

refactor: pull out common CLI into a base structure

---

env.go

I noticed that the check is occurring even on search, eg.
🐚 ~/Development/orc $ hermit search cashcache
info:cashkite-conventional-commits@stable: No updated required
info:go@latest: No updated required
cashcache (@0, @0.0, @latest, 0.0.18, 0.0.21, 0.0.23, 0.0.25, 0.0.27, 0.0.28, 0.0.29, 0.0.30, 0.0.31)
cashcache is CI cache to improve build times

fix: only sync packages if forced or update frequency is hit

---

go.mod
go.sum
hermittest/envfixture.go
internal/dao/dao.go

Just use the .etag file's mtime for UpdatedAt timestamps rathern than a
separate file.

refactor: simplify file-based DAO

---

.golangci.yml
archive/archive.go
env.go
internal/system/system.go
manifest/resolver.go
shell/bash.go
shell/zsh.go

Some tools/libraries such as AWS Lambda emulators strip down the
environment before being executed. We want Hermit to be able to
work in these situations so this implements custom functions
to work around this.
Fixes #239

fix: use custom UserHomeDir and UserCacheDir

---

bin/hermit.hcl
env.go

This allows executables that find related files relative to their binary, such as Python, to work.
I cannot think of a real downside here, but behaviour will be slightly different.

fix: replace argv[0] when proxying to binaries

---

.github/workflows/canary.yml

The ScriptSHA for the corresponding `bin/hermit` has already been added.

fix: publish versioned installer script to canary

---

env.go
env_test.go

One code path would setup environment variable overrides in the order of: _(later beats earlier)_
1. Packages
2. `PATH`
3. `HERMIT_BIN` / `HERMIT_ENV`
4. The local `hermit.hcl`
5. Command-line parameters
And another would do it in order of:
1. Packages
2. The local `hermit.hcl`
3. `PATH`
4. Runtime dependencies
5. `HERMIT_BIN` / `HERMIT_ENV`
6. Command-line parameters
This refactor refactors to a single codepath in the order of:
1. `PATH` / `HERMIT_BIN` / `HERMIT_ENV` (now inseparable)
2. Runtime dependencies
3. Packages
4. The local `hermit.hcl`
5. Command-line parameters
A test is attached. A _better_ test would define the priority order of these overrides … but that's for a better person than me.

Normalise environment variable substitution

---

app/command_info_test.go
app/info_cmd.go
app/list_cmd.go
app/search_cmd.go

This PR let `list` and `search` command able to print out Machine readable JSON output.
Also creates `JSONFormattable` flag shared among `info`, `list`, and `search` command.

feat: add json format to list and search

---

app/list_cmd.go
app/search_cmd.go

This PR streamlined the output of search result
an example of the result looks like this
`go run ./cmd/hermit search "^go$|hugo" --json | jq | pbcopy`
```
[
{
"Name": "go",
"Versions": [
"1.17rc1",
"1.18beta1",
"1.18beta2",
"1.13.5",
"1.14.4",
"1.14.7",
"1.15.2",
"1.15.3",
"1.15.6",
"1.15.7",
"1.15.11",
"1.16",
"1.16.3",
"1.16.4",
"1.16.5",
"1.16.6",
"1.16.7",
"1.17",
"1.17.1",
"1.17.2",
"1.17.3",
"1.17.7",
"1.17.8",
"1.17.9",
"1.17.10",
"1.18",
"1.18.1",
"1.18.2"
],
"Channels": [
"@1",
"@1.13",
"@1.14",
"@1.15",
"@1.16",
"@1.17",
"@1.18",
"@latest",
"@tip"
],
"CurrentVersion": "1.17.10",
"Description": "Go is an open source programming language that makes it easy to build simple, reliable, and efficient software."
},
{
"Name": "hugo",
"Versions": [
"0.82.0",
"0.84.3",
"0.84.4",
"0.85.0", …
```

fix: streamlined search output

---

app/list_cmd.go
app/search_cmd.go

This PR fixes errors in the argument passing in both list and search command
1. list command should call `listPackages`
2. search command should pass in AllVersions = true in the options for CLI output

fix: call listPackages in List command and fix allVersions in Search command CLI

---

app/search_cmd.go
manifest/config.go
manifest/resolver.go
manifest/resolver_repository_test.go

This PR add Repository attribute in the Manifest and Package struct
1. If it is not specified in the Manifest struct, it will try to infer it from package's source url
2. Passing the Repository attribute in Package struct so that we could have it in the info/list/search commands
Purpose of this is to have the repository url so that renovate could lift this up and fetch changelog/release note when constructing the PR.

feat: add Repository attribute in Manifest and Package  struct, will infer if empty

---

manifest/resolver.go
manifest/resolver_repository_test.go

This PR picks up github repository from auto-version => github-release. Making it easy form some repository on github but ship their releases from places other than github
example.
```
go run ./cmd/hermit search consul --json | jq                         ─╯
[
{
"Name": "consul",
"Versions": [
"1.9.17",
"1.10.3",
"1.11.1",
"1.11.2",
"1.11.3",
"1.11.4",
"1.11.5",
"1.12.0"
],
"Channels": [
"@1",
"@1.10",
"@1.11",
"@1.12",
"@1.9",
"@latest"
],
"CurrentVersion": "",
"Description": "Consul is a distributed, highly available, and data center aware solution to connect and configure applications across dynamic, distributed infrastructure.",
"Repository": "https://github.com/hashicorp/consul"
}
]
```
also source of the concul hermit-packages …

fix: pick up repository from auto-version => github-release

---

sources/git.go
sources/git_test.go
sources/sources.go
util/run.go

Turns out that we were removing the source directory before running `git clone` If that failed, the directory was removed, leading to potentially wrong manifests being used from separate sources.
Fixes https://github.com/cashapp/hermit/issues/282

fix: Do not remove source dir from disk if both pull and clone fail

---

app/commands.go
app/main.go
state/state.go
util/flock.go
util/flock_test.go

This PR provides `--lock-timeout` flag in the CLI to make acquire lock timeout from a hard coded `30s` to configurable via CLI. 
default value is set to `30s` so it would have no impact for current users .

feat: configurable lock timeout

---

app/commands.go

This PR make --lock-timeout flag able to take from environment variable `HERMIT_LOCK_TIMEOUT`

fix: add environment variable for hermit lock timeout

---

app/search_cmd.go

checks for exact package name match only.
an alternative approach is to add the `exact` flag to `(*Resolver).Search` - which would have the benefit of being faster (fewer packages to manage) but would add more complexity to an already complex function. happy to make that change instead if you'd prefer!
test cases
```
▶  go run cmd/hermit/main.go search python -e
(returns nothing, no exact matches)
▶ go run cmd/hermit/main.go search go -e
go (@1.15, @1.16, @1.17, 1.17rc1, @1, @1.13, @1.14, @1.18, @latest, 1.18beta1, 1.18beta2, 1.19beta1, @tip, 1.13.5, 1.14.4, 1.14.7, 1.15.2, 1.15.3, 1.15.6, 1.15.7, 1.15.11, 1.16, 1.16.3, 1.16.4, 1.16.5, 1.16.6, 1.16.7, 1.17, 1.17.1, 1.17.2, 1.17.3, 1.17.7, 1.17.8, 1.17.9, 1.17.10, 1.18, 1.18.1, 1.18.2, 1.18.3)
Go is an open source programming language that …
```

feat: add exact flag to search

---

manifest/loader.go

Because they were produced from a map, the order was random leading to
different outputs. We're going to start using this for a package index,
so this would produce frequent diffs.

fix: synthesised channels were not deterministic

---

env.go

Currently only a package name can be specified, but it's sometimes the
case that we need to specify an explicit version or version channel.

fix: allow `requires = [...]` to secify versions

---

manifest/config.go
manifest/resolver.go

This change makes it possible to do package sha256 check during package
installation for autoversioned packages. We do so by using an attribute
named `sha256sums` in the package manifest file, which is a map of
format
{
source1: source1_sha256,
source2: source2_sha256
}
e.g,
sha256sums = {
"https://github.com/syncom/sf-signer/releases/download/v0.0.0/sfsigner-darwin-x86_64": "3e8692fa751983b75b11392968b6244e48b8b56a3363257286840ac35a696c06",
"https://github.com/syncom/sf-signer/releases/download/v0.0.0/sfsigner-linux-x86_64": "7cfd5c00b8bc7215bc99972017da1837c514856db6d72b8e44e9136cb4fe9054"
}
When the package sha256 checksums in the `sha256` and `sha256sums`
attributes do not agree, the `sha256` attribute takes precedence over the
`sha256sums` attribute, for package integrity …

Support autoversion package sha256 verification

---

docs/content/usage/renovate.md

This PR adds a section for Renovate describing 
* managing Hermit package update with Renovate
* using Hermit as a binary source for Renovate.

fix: add Renovate documentation for Hermit

---

Makefile
app/exec_cmd.go
app/main.go
env.go
it/full/spec/it_spec.sh

Support running hermit from different environments

---

github/api.go
manifest/autoversion/autoversion.go
manifest/autoversion/autoversion_test.go
manifest/autoversion/github.go
manifest/autoversion/github_test.go

Previously, it only looked at the last release. If multiple releases are published at the same time, and the latest one is invalid, hermit will not pick up any new releases.

fix: ignore-invalid-versions will iterate releases

---

.github/workflows/ci.yml
go.mod
go.sum
integration/integration_test.go

It turns out that shellspec is not a great experience. This doesn't currently attempt to remove any of the shellspec tests, just allow us to write new tests in Go.

feat: add Go-based integration testing

---

manifest/config.go
manifest/config_test.go

This will simplify some trickier packages that currently require a lot of duplication to work, such as [opa](https://github.com/cashapp/hermit-packages/blob/dd0f7b4e48b35354fae264e78ba5a6b82883a98d/opa.hcl#L29).

feat: allow "platform <pattern>" to match <os>-<arch>

---

manifest/resolver.go

A bit more thought should be put into how this should be handled more globally (eg. filter out invalid entries from being returned by All() at all) but for now this will suffice.

fix: don't use manifests that have errored

---

.gitignore
manifest/config.go
manifest/digest/digest.go
manifest/resolver.go

This is an optional URL to a sha256 checksum file used as an optimisation when adding digests to manifests. Parsing of the file is very lenient and if anything fails, the update will fall back to downloading and computing the digest manually.

Add a "sha256-source" attribute.

---

app/exec_cmd.go
env.go

This manifested because the gradle package depends on "jre". The installed JRE satisfied this constraint initially but was later upgraded. Because dependency resolving didn't set syncOnMissing, this resulted in a "package not found" error.

fix: ensure missing package dependencies trigger a sync

---

.github/workflows/ci.yml
.gitignore
app/validate_script_cmd.go

This is best-effort, as it's impossible to do this statically in the general case.

fix: recursively collect function decls when validating shell scripts

---

app/auto_version_cmd.go

There are auto-versioning errors nearly every day. This is very tiresome to keep on top of. This change will version as many packages as possible, but log any failures so that periodically the failing packages can be checked and fixed.

feat: add --continue-on-error to auto-version

---

manifest/config_test.go
manifest/resolver.go

(cashapp#288) Addresses error messaging on invalid version

---

README.md

It looks like we broke some links in the README with the move to mkdocs in #358

Fix links to static resources in the README

---

app/env_cmd.go
shell/shell.go

This allows you to force printing of activation/deactivation code for shells other than the current (auto-detected) one, which is handy for testing.

Add "--shell" option to "env" subcommand

---

app/list_cmd.go
go.mod
ui/ui.go

From pkg.go.dev:
> Deprecated: this package moved to golang.org/x/term.

chore: remove dependency on deprecated golang.org/x/crypto/ssh/terminal

---

manifest/manifesttest/pkgbuilder.go
manifest/resolver.go
state/state.go
state/state_test.go

The fast-path check to short-circuit locking was buggy becaues it was statting the `Package.Binaries` slice without glob expansion. That is, it ended up statting globs like `bin/*`, resulting in frequent unnecessary locking.

fix: buggy lock-free fast-path check

---

state/state.go

We use double-checked locking to avoid locks on the fast-path, but I modified the behaviour in #390 to cache the result before the lock, removing the second check. Face palm.
This fixes #391

fix: double-checked locking fail

---

docs/docs/faq/index.md

This updates the documentation to support `fish` shell using a workaround via `direnv`.

docs: add workaround for `fish` shell

---

docs/docs/usage/config.md
env.go
integration/integration_test.go
integration/testdata/environment_inheritance/bin/README.hermit.md
integration/testdata/environment_inheritance/bin/activate-hermit
integration/testdata/environment_inheritance/bin/hermit
integration/testdata/environment_inheritance/bin/hermit.hcl
integration/testdata/environment_inheritance/child_environment/bin/README.hermit.md
integration/testdata/environment_inheritance/child_environment/bin/activate-hermit
integration/testdata/environment_inheritance/child_environment/bin/hermit
integration/testdata/environment_inheritance/child_environment/bin/hermit.hcl
integration/testdata/environment_inheritance/child_environment/packages/binary.hcl
integration/testdata/environment_inheritance/child_environment/packages/binary.sh
integration/testdata/environment_inheritance/packages/binary.hcl
integration/testdata/environment_inheritance/packages/binary.sh

Adds a new environment configuration to bin/hermit.hcl
```
inherit-parent = true
```
Setting this inherits the Hermit environment from a parent directory, inheriting environment variables and packages.
This should be useful in larger monorepos where we want to have a single root environment with most tooling, but want to still allow subprojects to have their own owerwrites and environment variables.
Note, the packages in parent environment won't have access to the child environment even when being called from the child environment. This means that any package calling another package in the parent environment will still call the parent package even if that is overwritten in the child environment. Though this can be potentially confusing, it should give more consistent behaviour between …

feat: support extending a parent environment

---

docs/docs/usage/ide.md

Added a new section "Visual Studio Code terminal" that provides guidance on using Hermit with the VS Code terminal.

Add docs for vscode terminal workaround

---

cache/http.go

context: when hitting a download error the log only has the url in hermit manifest but not the one from the source.
we are trying to figure out why hermit is getting 429 which does seem to come from github straight instead of the internal source url.

fix: log source url on http download failure

---

app/install_cmd.go
sources/sources.go

This occasionally breaks enabling the hermit IntelliJ plugin that installs dependencies automatically at startup.
We also skipt the test if we had synchronized previously if we are forcing a sync. This is needed as "hermit install" does a non forced sync at the beginning, marking source as synced, and this prevents the later forced sync from running when the package is not found.
Fixes https://github.com/cashapp/hermit/issues/363

fix: sync packages if "hermit install" fails to find a package

---

app/auto_version_cmd.go
app/log_test.go
app/user_config.go
archive/archive.go
archive/archive_test.go
cache/http.go
env.go
env_test.go
hermittest/envfixture.go
integration/integration_test.go
sources/git.go
sources/git_test.go
state/stateutils_test.go
util/filepatcher.go
util/filepatcher_test.go
util/flock_test.go

ioutil is deprecated and shouldn't be used anymore.
Drop all uses in favor of equivalent functions from os and io.

Drop ioutil

---

manifest/autoversion/github.go

In case of updating nodejs/node v17 - the last v17 tag is more than 100 tags behind the latest, causing the existing auto-version logic to fail.
We will fix this further by supporting to update auto-version of a specific version (instead of today's logic to go through all the auto-versioned packages).

fix: Increase github version lookup to 200

---

app/activate_cmd.go
app/exec_cmd.go
app/main.go
app/validate_env_cmd.go
cache/github.go
cache/github_test.go
env.go
env_test.go
hermittest/envfixture.go

Adds a new per-project configuration to hermit.hcl
allowing opting GitHub owner/repo patterns to opt into
token-based authentication instead of anonymous.
For example:
github-auth-token {
match = ["cashapp/*"]
}
The option accepts any number of glob patterns,
allowing for fine-grained control over which dependencies
get authenticated requests.
This will make it possible to use Hermit with private repositories
without distributing a custom build.
The plumbing for this required a small amount of refactoring:
The new hermit.LoadEnvInfo inspects a Hermit environment
and loads the configuration, but does not open the environment.
The information is later passed to the old hermit.OpenEnv function.
This separation is necessary because cache and state are inputs to
OpenEnv, but we need to inspect …

config: Support opting into GitHub token auth

---

docs/docs/faq/index.md

Ruby has been supported since 2022, so this section should be removed to avoid confusion.

doc(faq): remove section about a lack of support for ruby

---

app/commands.go
app/noop_cmd.go
shell/bash.go
shell/zsh.go

Completion by default will pass the entire command to the completion program's Argv. Kong isn't able to handle this, so update the completion command to use the noop subcommand. The noop subcommand has to be updated to accept and discard any additional arguments.

fix: broken shell completion

---

integration/integration_test.go

The output of shell commands was being read in a goroutine, but the test wasn't waiting for the IO to finish. This caused the expectations to sometimes fail. Fix by reading the output synchronously. This does not have a significant effect on the test execution time.

test(integration): fix flaky test

---

app/main.go
ui/ui.go

app.Main spawns a goroutine to periodically flush output buffers to stdout and stderr. However, it does so without acquiring the log writer's lock. Add a Sync method to UI so that we can ensure that the mutex is acquired before flushing the buffers.
This change is more theoretical than anything. I discovered it by using `go build -race` rather than after having observed any real symptoms. It may or may not be related to #333.

fix(app): unsafe stdout buffer management

---

docs/docs/usage/shell.md
shell/files/fish_hooks.fish
shell/hooks.go

Configures fish shell completions to work with kongplete. Update shell-hooks docs to include fish.

fish completions, update docs

---

docs/docs/usage/shell.md
env.go

env validation was failing when the `activate-hermit.fish` script was missing due to matching on path instead of filename. Not sure why integration tests didn't catch it. Will follow up later with a test.

fix: env validation when missing fish script

---

env.go
manifest/loader.go

Consists of two changes.
Previously, when `hermit exec` was run on a package with a `requires`
field, it would parse every known package to gather a list of candidates
to fulfill the requirement. In the vast majority of cases, the user will
already have the dependent package installed, so optimize by first
evaluating only the installed packages. This change has no appreciable
effect on the negative path where we *do* end up parsing all known
packages. The result is a speedup by about a factor of 5 to 10 on my machine.
Add concurrency to Loader.All by parsing each hcl file in a separate
goroutine. This results in an execution time that is about 3x faster on
my machine. This change is most visible when Hermit must parse all
packages during `hermit exec`.
Ran with `-race` to ensure I got the …

perf: speedup hermit exec

---

integration/integration_test.go

Follow up test for https://github.com/cashapp/hermit/pull/427. Verifies that an otherwise valid hermit environment missing an `activate-hermit.fish` is still considered valid.

chore: add integration test for missing activate-hermit.fish

---

it/full/run.sh
manifest/autoversion/git_tags_test.go

Makes the test more robust by explicitly disabling GPG signing in the test repository. This ensures the tests works consistently in environments where commit signing is enabled globally (e.g., developers using 1Password or other GPG signing tools).

fix: Explicitly disable GPG signing in git tags test

---

Makefile
app/activate_cmd.go
app/commands.go
app/init_cmd.go
app/main.go
app/user_config.go
docs/docs/usage/user-config-schema.hcl
integration/integration_test.go

Adds support for user-level configuration defaults in Hermit. Users can now define default settings in their ~/.hermit.hcl file that will be applied to all new Hermit environments.
**Example ~/.hermit.hcl:**
```hcl
defaults {
sources = [
"https://github.com/lox/private-hermit-packages.git", 
"https://github.com/cashapp/hermit-packages.git"
]
}
```
Also allows the user config file to be defined with `HERMIT_USER_CONFIG` or `--user-config`. 
This replaces the more narrowly scoped https://github.com/cashapp/hermit/pull/434.

feat: Allow defining defaults for hermit.hcl in user config

---

env.go

In a nested environment, Hermit fails to set the correct environment for the target binary. For example, given the following directory structure:
```
repo-root/
├── bin/
│   ├── java@17
│   ├── gradle
├── foo/
│   ├── bin/
│   │   ├── java@21
```
When navigating to `repo-root/foo` and running `gradle`, Hermit installs Java 17 but sets `JAVA_HOME` to Java 21, resulting in the following error:
```
JAVA_HOME is set to an invalid directory: /root/.cache/hermit/pkg/openjdk@21
```
This issue leads to unexpected failures in internal builds.
This commit reverts cashapp/hermit#433 because it introduces a regression in environment resolution. Until a proper fix is found, reverting ensures stability for existing builds.

fix: Revert "perf(exec): improve performance"

---

shell/files/sh_common_hooks.sh

For my own sanity's sake, I use `set -u` as part of my zsh config. However, hermit's `change_hermit_env` command fails when this is enabled; this PR fixes the hook so that when variables aren't set it won't emit the following error:
```sh
% cd ~/tmp/testing
change_hermit_env:3: HERMIT_ENV: parameter not set                                                                                                                                         
%
```

[change_hermit_env] Gracefully handle set -u in change_hermit_env

---

docs/docs/packaging/private.md
docs/docs/usage/config.md

This rebases and updates https://github.com/cashapp/hermit/pull/413 by @abhinav. Never tried to do this not as a maintainer before, so apologies if I've done this wrong. Original PR description was
> PR #409 added support for opting packages into GitHub token authentication with a `github-token-auth` block in `bin/hermit.hcl`.
> 
> This adds information about this feature to the private releases documentation, and adds an entry to the config reference.

docs: Add github-token-auth documentation (rebased #413)

---

Makefile

Recently, I made a change, ran `make test-integration` locally, got cached results, pushed the change and it failed.
So I thought maybe the integration tests shouldn't be cached. I found this solution https://stackoverflow.com/a/48882892

chore: Always run all the integration tests

---

.github/workflows/ci.yml

The docs exclusion saves a small amount of time for a doc-only change, but at the moment, the PR never runs the checks, so doesn't get marked as ready to merge!
We could update the checks, but feels simpler to just remove the doc exclusion.

chore: Remove docs exclusion from CI runs

---

env.go
integration/integration_test.go
integration/testdata/environment_inheritance/child_environment/packages/envprovider.hcl
integration/testdata/environment_inheritance/child_environment/packages/envprovider.sh
integration/testdata/environment_inheritance/packages/envprovider.hcl
integration/testdata/environment_inheritance/packages/envprovider.sh
integration/testdata/environment_inheritance/packages/parentbin.hcl
integration/testdata/environment_inheritance/packages/parentbin.sh
integration/testdata/testenv2/packages/testbin4
integration/testdata/testenv2/packages/testbin4.hcl

The previous attempt in 9a9737ec668f5aa01cb8a2b83d5832654d6e4997 (#433) had an invalid method of detecting when environment variables needed to be parsed, so it was reverted in cc90510721cc58923414ce1efd339b3e2ffb20b8 (#442). This attempt takes the approach of instead checking if the binary being executed is inside the currently activated environment. If not, then we load the environment variables of all packages in the exec'd binary's environment. It may be possible to get away with only parsing the package's dependencies, but I'm not confident that would correctly handle all present use cases.

perf(exec): improve performance

---

app/main.go
ui/ui.go

Replace direct calls to `os.Exit` with `Kong.Exit` to ensure proper Kong exit handling

Use kong exit

---

manifest/version.go

ParseVersion was using regex to split strings into fields where strings.FieldsFunc will suffice. This regex split was taking a surprisingly large amount of CPU - changing to FieldsFunc reduces execution time of `hermit search go` by more than 10%:
Before change:
$ time hermit search go | wc
202    4805   35460
real    0m1.840s
user    0m3.335s
sys     0m0.233s
With change:
$ time hermit search go | wc
202    4805   35460
real    0m1.543s
user    0m2.897s
sys     0m0.258s

perf(manifest): speed up ParseVersion

---

bin/lint-shell-exit-codes
bin/lint-shell-scripts
integration/integration_test.go
it/full/spec/it_spec.sh
shell/files/activate.tmpl.fish
shell/files/activate.tmpl.sh

We've had reports of some AI agents struggling when trying to activate an already activated environment because of the non-zero exit code. There reason for exiting with the 34 code seems to have been lost to the sands of time, and we now believe that there is not a significant reason not to exit cleanly in this case.

fix: skipping activation when already activated should exit cleanly

---

env.go
manifest/resolver.go

If the required binaries are missing it indicates there was a problem with the installation of the package being used.  
Updates the error messages so that it's clearer how the user can potentially remedy the situation.
There are three scenarios that I manually tested:
- `bin` directory missing.
- `bin` directory empty.
>fatal:hermit: node-22.14.0: failed to resolve package binaries - this may indicate a corrupted installation, try removing /Users/jrobotham/Library/nodejs/nodejs-22.14.0-block-2024 and hermit will reinstall it (may require sudo)
- required binary missing.
>fatal:hermit: node-22.14.0: failed to resolve binary "node" in installed package - this may indicate a corrupted installation, try removing /Users/jrobotham/Library/nodejs/nodejs-22.14.0-block-2024 and hermit will …

fix: Improve error message when binaries are missing

---

envars/util.go
envars/util_test.go
manifest/resolver.go

While working on an implementation for #312, I found that it was necessary to factor variable expansion logic out of the manifest package so that it can be used elsewhere, such as when parsing hermit.hcl. This does not necessarily make the existing code cleaner, but it will facilitate future changes.
Also fixes an issue where variable references without {} (e.g., $FOO) were in some cases left unexpanded.

refactor: move common variable expansion to envars package

---

app/main.go

The memory profile was being created before the main program even started, so very little relevant data was recorded. Also update the default view to total allocations since the program started rather than the current heap.

fix: incomplete memory profile

---

docs/docs/usage/updates.md

Link on this page: https://cashapp.github.io/hermit/usage/updates/
is currently dead
Correct link is to this:
https://cashapp.github.io/hermit/packaging/reference/#update-policy

docs: Fix link to package updates policy

---

it/sanity/run.sh
state/state.go
state/state_test.go

When running hermit on an NFS mounted environment, it fails to update itself. This is due to NFS keeping a  file busy while a binary on a certain folder is executing. Reference similar issue: https://community.unix.com/t/unix-rm-rf-error-rm-cannot-remove-filename-device-or-resource-busy/288520/7
Solution: 
- If self-updating hermit, instead of removing all files, rename folder to allow for new installation to happen. This ensures we don't have issues on NFS-like file systems.
Run of sanity/run.sh showing error:
```
file:///home/gerardc_squareup_com/projects/hermit/it/sanity/release/canary
~/projects/hermit/it/sanity/testenv ~/projects/hermit/it/sanity
info: Creating new Hermit environment in /home/gerardc_squareup_com/projects/hermit/it/sanity/testenv
info:   -> …
```

Fix self-update for NFS

---

app/exec_cmd.go
app/main.go

Since the hashed cached source path changes based on the rewritten URL, we can fail to run commands when relying on `HERMIT_GITHUB_TOKEN` for source authentication. This is a follow-up to cashapp/hermit#441 to use the same git source rewriting during exec.

fix: use HERMIT_GITHUB_TOKEN for git operations during exec

---

manifest/resolver.go
manifest/resolver_test.go

This situation is easy to run into when a field contains the ${version} variable but a channel does not contain a specific version range.

fix: improve error when version fails to expand

---

envars/util.go
envars/util_test.go
manifest/resolver.go
manifest/resolver_test.go

eg. in `swc.hcl` this:
```hcl
vars = {
"arch_": "${arch}",
"suffix": "",
}
```
Results in many errors like this:
```
warn: invalid manifest reference swc-1.10.16 in swc.hcl: unknown variable $suffix
```

fix: valid but empty variables in manifests were resulting in errors

---

.github/workflows/release.yml
Makefile
app/exec_cmd.go
app/update_cmd.go
env.go
state/state.go

This was a regression I introduced in #507.

fix: don't rely on an environment when self updating

---

docs/docs/packaging/reference.md

Just happened to click on these to double check the values and noticed the paths had changed.

chore: fix syslist links in docs
